<?php $_results = $this->getResults() ?>
<?php $_catalogSearchHelper =  $this->helper('catalogsearch'); ?>

<div class="loop54-autocomplete-list">
    <?php foreach ($_results as $_result): ?>
        <p class="loop54-autocomplete-item">
            <a href="<?php echo $_catalogSearchHelper->getResultUrl() ?>?<?php echo $_catalogSearchHelper->getQueryParamName() ?>=<?php echo $this->htmlEscape($_result->string) ?>"><?php echo $this->htmlEscape($_result->string) ?></a>
        </p>
    <?php endforeach ?>
</div>